---
assignees:
  - ponfertato
commitMessages:
  graphsUpdate: ':bento:graphs: update'
  readmeContent: ':pencil:README: update'
  statusChange: ':stethoscope:$SITE_NAME: $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms)'
  summaryJson: ':card_file_box:summary: update'
i18n:
  footer: ''
owner: potatoenergy
repo: status
sites:
  - name: Open WebUI
    method: POST
    url: https://chat.potatoenergy.ru/health
    headers:
      - "Content-Type: application/json"
    body: '{"status":true}'
  - expectedStatusCodes:
      - 200
      - 201
      - 202
      - 203
      - 200
      - 204
      - 205
      - 206
      - 207
      - 208
      - 226
      - 300
      - 301
      - 302
      - 303
      - 304
      - 305
      - 306
      - 307
      - 308
      - 401
    method: GET
    name: Nextcloud
    url: https://cloud.potatoenergy.ru/login
  - method: HEAD
    name: Mastodon
    url: https://social.potatoenergy.ru/health
  - check: tcp-ping
    name: Mindustry
    port: 6567
    url: connect.potatoenergy.ru
  - check: tcp-ping
    name: Minecraft
    port: 25565
    url: connect.potatoenergy.ru
status-website:
  cname: status.potatoenergy.ru
  introTitle: 🕒 Проект работает ежедневно с 08:00 по 00:00.
  logoUrl: https://avatars.githubusercontent.com/u/137938438?s=200&v=4
  name: Potato Energy
  navbar:
    - href: https://potatoenergy.ru/
      title: Home
    - href: https://github.com/potatoenergy
      title: GitHub
    - href: https://codeberg.org/potatoenergy
      title: Codeberg
user-agent: potatoenergy
