---
assignees:
  - ponfertato
i18n:
  activeIncidentSummary: 'Создан $DATE, сообщений: $POSTS'
  activeIncidents: Активные инциденты
  allSystemsOperational: Все системы работают штатно
  averageResponseTime: 'Среднее время ответа: $TIME мс'
  averageResponseTimeTitle: Среднее время ответа
  degraded: Частичный сбой
  down: Недоступно
  duration: Длительность
  duration1Y: 1 год
  duration24H: 24 ч
  duration30D: 30 дн
  duration7D: 7 дн
  durationAll: Всё
  durationMin: $DURATION мин
  errorHome: На главную
  errorIntro: Не удалось получить данные о статусе
  errorText: Попробуйте позже
  errorTitle: Ошибка
  footer: ''
  incidentBack: ← Ко всем инцидентам
  incidentClosedAt: Закрыт
  incidentCommentSummary: 'Опубликовано $DATE, автор: $AUTHOR'
  incidentCompleted: Завершён
  incidentDetails: Подробности инцидента
  incidentFixed: Исправлен
  incidentOngoing: Активен
  incidentOpenedAt: Открыт
  incidentReport: 'Отчёт об инциденте #$NUMBER →'
  incidentScheduled: Запланирован
  incidentTitle: Детали инцидента $NUMBER
  incidentViewOnGitHub: Просмотреть и подписаться на GitHub
  liveStatus: Текущий статус
  loading: Загрузка...
  locale: ru-RU
  ms: мс
  navGitHub: GitHub
  overallUptime: 'Общая доступность: $UPTIME'
  overallUptimeTitle: Общая доступность
  pastIncidents: Завершённые инциденты
  pastIncidentsResolved: Решено за $MINUTES минут ($POSTS сообщений)
  pastScheduledMaintenance: Завершённые работы
  rateLimitExceededCopyPastePAT: 'Вставьте ваш токен:'
  rateLimitExceededErrorFix: Подождите час или добавьте персональный токен GitHub для 5000 запросов/час.
  rateLimitExceededErrorHowCanFix: Как исправить?
  rateLimitExceededErrorMeaning: Сайт использует GitHub API с лимитом 60 запросов/час с одного IP.
  rateLimitExceededGeneratePAT: Создать персональный токен
  rateLimitExceededGitHubPAT: GitHub-токен
  rateLimitExceededHasSet: Токен активирован
  rateLimitExceededIntro: Вы превысили лимит запросов в час. Подождите или используйте GitHub-токен для продолжения.
  rateLimitExceededRemoveToken: Удалить токен
  rateLimitExceededSaveToken: Сохранить
  rateLimitExceededTitle: Превышен лимит запросов
  rateLimitExceededWhatDoesErrorMean: Что это значит?
  responseTimeMs: Время ответа (мс)
  scheduledMaintenance: Плановые работы
  scheduledMaintenanceSummaryStarted: Начато $DATE ($DURATION мин)
  scheduledMaintenanceSummaryStarts: Запланировано $DATE ($DURATION мин)
  sevelDayResponseTime: Динамика ответов за 7 дней
  startedAt: Начато
  startsAt: Запланировано
  up: Доступно
owner: potatoenergy
repo: status
sites:
  - icon: https://icons.duckduckgo.com/ip3/grafana.com.ico
    method: GET
    name: Grafana
    # slug: grafana
    url: https://grafana.potatoenergy.ru/api/health
  - icon: https://icons.duckduckgo.com/ip3/joinmastodon.org.ico
    method: HEAD
    name: Mastodon
    # slug: mastodon
    url: https://social.potatoenergy.ru/health
  - expectedStatusCodes:
      - 200
      - 302
      - 303
      - 401
    icon: https://icons.duckduckgo.com/ip3/nextcloud.com.ico
    method: GET
    name: Nextcloud
    # slug: nextcloud
    url: https://cloud.potatoenergy.ru/login
  - expectedStatusCodes:
      - 200
      - 302
      - 303
      - 405
    icon: https://icons.duckduckgo.com/ip3/openwebui.com.ico
    method: GET
    name: Open WebUI
    # slug: open-webui
    url: https://chat.potatoenergy.ru/health
  - check: tcp-ping
    icon: https://icons.duckduckgo.com/ip3/mindustrygame.github.io.ico
    name: Mindustry
    port: 6567
    # slug: mindustry-server
    url: connect.potatoenergy.ru
  - check: tcp-ping
    icon: https://icons.duckduckgo.com/ip3/www.minecraft.net.ico
    name: Minecraft
    port: 25565
    # slug: minecraft-server
    url: connect.potatoenergy.ru
  - check: tcp-ping
    icon: https://icons.duckduckgo.com/ip3/www.terraria.org.ico
    name: Terraria
    port: 7777
    # slug: terraria-server
    url: connect.potatoenergy.ru
  - check: tcp-ping
    icon: https://icons.duckduckgo.com/ip3/drawpile.net.ico
    name: Drawpile
    port: 27750
    # slug: drawpile
    url: connect.potatoenergy.ru
  - check: tcp-ping
    name: API
    # slug: api
    url: connect.potatoenergy.ru
status-website:
  cname: status.potatoenergy.ru
  introTitle: 🥔 **Potato Energy** — где клубни традиций прорастают в IT-инновации
  logoUrl: https://avatars.githubusercontent.com/u/137938438?s=200&v=4
  name: Potato Energy
  navbar:
    - href: https://potatoenergy.ru/
      title: Home
    - href: https://github.com/potatoenergy
      title: GitHub
    - href: https://codeberg.org/potatoenergy
      title: Codeberg
  themeUrl: https://status.potatoenergy.ru/dark.css
user-agent: potatoenergy
workflowSchedule:
  graphs: 0 0 * * *
  responseTime: 0 23 * * *
  staticSite: 0 1 * * *
  summary: 0 0 * * *
  updateTemplate: 0 0 * * *
  updates: 0 3 * * *
  uptime: '*/5 * * * *'
